RENDER_OUTPUT_PATH = "//control_net_images"
IMG_2_IMG_NAME = "ControlNet img2img"
DEPTH_NAME = "ControlNet Depth"
NORMAL_NAME = "ControlNet Normal"
EDGE_NAME = "ControlNet Edge"
SD_OUTPUT_NAME = "Stable Diffusion Output"
